### PR TITLE
Fh 3446 new sync api doc

### PR DESCRIPTION
**Pull request by wei-lee**
This PR will:

* Add documentations for all the APIs in the new sync framework. Each API has its own doc page and a new landing page is added to link them together.
* Add new instructions about how to scale the sync server to multiple apps on SAAS.

ping @david-martin for review.

### CODE REVIEW

**Comment by paolobueno** [comment]
@wei-lee Definitely a great writeup!
I was just wondering, were the API docs written by hand?
I think we'd greatly benefit from generating them from JSDoc annotations to keep them in sync.

Something like running them through [this package](https://www.npmjs.com/package/jsdoc-to-markdown) and then convert from markdown to asciidoc through some other tool like pandoc.

**Comment by wei-lee** [comment]
@paolobueno Great idea. I was talking to @david-martin and @jasonmadigan about this yesterday. It will save us a lot of time if the asciidoc can be generated from the JSDoc. But we didn't find anything that can do it. So we decide to write the docs first, then maybe spend some time afterwards to see how hard it is to do the auto generation. But I think your approach is easier to implement. Just not sure how well pandoc can convert markdown to asciidoc.

Have you used it before?

**Comment by david-martin** [comment]
@wei-lee I'm taking a read through this now

**Comment by david-martin** [comment]
@wei-lee @paolobueno something to consider if/when moving to generating some/all fo the API docs from code is how this could work for other APIs too e.g. the Android & Objective C client API?

**Comment by paolobueno** [comment]
@david-martin I think each of those languages has their own 'standards' as in a most common tool for documentation through comment blocks.
Thankfully javadoc is probably very close to jsdoc, and for the other languages there are hopefully equivalents.
As long as we can reach a similar resulting document structure, i.e. `<h3>` for function names, etc., we can probably convert it to asciidoc through pandoc.

**Pull request merged**
